### ISSUE TITLE
Hello-World tutorial init needs python3

### ISSUE THREAD

**Issue by harvv** [SEL4PROJ/docs#37]
On an Ubuntu 18.04 system, unless python3 dependencies have been installed specifically using pip3 (instead of pip), when the system has both python 2 and python 3 installed, the 'init' script of the hello-world tutorial seems to fail (with missing module errors)

The HostDependencies page instructs that both versions of python-dev and python3-dev be installed (and implicitly thus, python(2) and python3).  However, the rest of the page instructs python dependencies to be installed with 'pip' (and not pip3).

This apparently causes a problem when the tutorial init scripts try to run, as this appears in an included script  (  seL4-tutorials-manifest/projects/sel4-tutorials/common.py )
`#!/usr/bin/env python3 `

Possible solution:
Once all the commands from HostDependencies were re-run with "pip3" substituted for "pip"  (and additionally, the two pip install commands in  Tutorials/#get-the-code  likewise with pip3 substituted),  the tutorial init scripts seemed to run to successful completion

**Comment by Ben-PH** [comment]
I parsed the issue as part of looking into it. Here is my transcription.

System: Ubuntu 18.04

issue: 'init' script

[Host Dependencios](https://docs.sel4.systems/HostDependencies):  instructs `python-dev` and `python3-dev` to be installud

Suspected root cause: 

- Implicitly requiring both `python2` and `python3`
- Asking python dependencies to be installed with `pip`, not `pip3`

Result: python3 based scripts run into issues

Possible solution: `s/pip/pip3/` in [Host Dependencios](https://docs.sel4.systems/HostDependencies) and [tutorial code](https://docs.sel4.systems/Tutorials/#get-the-code).

My environment is not set-up right now to conveniently recreate the issue. That's going to change in the near future. 

My plan was to make VM  and A/B check the two on a fresh system (current/suggested change). Do a write-up showing what does/dosn't work. 

I intend to revisit this after exams.

**Comment by kent-mcleod** [comment]
I updated the dependencies page in 636b79776bf1eb1c1f69f666b785443c8dce0b38 to add python2 and python3 installation requirements.  Thanks for reporting.
